version: '3.8'

services:
  dvwa:
    image: vulnerables/web-dvwa
    restart: always
    ports:
      - "8081:80"
    networks:
      - vuln-net

  juice-shop:
    image: bkimminich/juice-shop
    restart: always
    ports:
      - "3000:3000"
    networks:
      - vuln-net

  mutillidae:
    image: citizenstig/nowasp
    restart: always
    ports:
      - "8082:80"
    networks:
      - vuln-net

  webgoat:
    image: webgoat/webgoat-8.0
    restart: always
    ports:
      - "8083:8080"
    networks:
      - vuln-net

  bwapp:
    image: raesene/bwapp
    restart: always
    ports:
      - "8084:80"
    networks:
      - vuln-net

  openvas:
    image: mikesplain/openvas
    restart: always
    ports:
      - "9392:9392"
    networks:
      - vuln-net

  nessus:
    image: tenableofficial/nessus
    restart: always
    ports:
      - "8834:8834"
    networks:
      - vuln-net

networks:
  vuln-net:
    driver: bridge